# Input files
obs_flow: "../drb-dl-model/data/in/obs_flow_subset"
obs_temp: "../drb-dl-model/data/in/obs_temp_subset"
sntemp_file: "../drb-dl-model/data/in/uncal_sntemp_input_output_subset"
dist_matrix: "../drb-dl-model/data/in/distance_matrix_subset.npz"

out_dir: "test_val_functionality"
code_dir: "/home/jsadler/river-dl/river_dl"

x_vars: ["seg_rain", "seg_tave_air", "seginc_swrad", "seg_length", "seginc_potet", "seg_slope", "seg_humid", "seg_elev"]
primary_variable: "flow"
lambdas: [100, 100]

train_start_date:
  - '1985-10-01'
  - '2016-10-01'
train_end_date:
  - '2006-09-30'
  - '2020-09-30'
val_start_date: '2006-10-01'
val_end_date: '2016-09-30'
test_start_date:
  - '1980-10-01'
  - '2020-10-01'
test_end_date:
  - '1985-09-30'
  - '2021-09-30'

pt_epochs: 1
ft_epochs: 1
hidden_size: 20
