# Input files
obs_file: "data_DRB/Obs_temp_flow_drb_Christiana"
sntemp_file: "data_DRB/sntemp_inputs_outputs_drb_Christiana"
dist_matrix: "data_DRB/distance_matrix_drb_Christiana.npz"

out_dir: "output_DRB_offsetTest"

code_dir: "river_dl"

x_vars: ["seg_rain", "seg_tave_air", "seginc_swrad", "seg_length", "seginc_potet", "seg_slope", "seg_humid", "seg_elev"]

y_vars_pretrain: ['seg_tave_water', 'seg_outflow']
y_vars_finetune: ['temp_c', 'discharge_cms']

lambdas: [1,0]

trn_offset: 1.0
tst_val_offset: 1.0


train_start_date:
  - '1985-10-01'
  - '2016-10-01'
train_end_date:
  - '2006-09-30'
  - '2020-09-30'
val_start_date: '2006-10-01'
val_end_date: '2016-09-30'
test_start_date:
  - '1980-10-01'
  - '2020-10-01'
test_end_date:
  - '1985-09-30'
  - '2021-09-30'

pt_epochs: 200
ft_epochs: 100
hidden_size: 20
