# Input files
obs_flow: "DRB_data/obs_flow_subset"
obs_temp: "DRB_data/obs_temp_subset"
sntemp_file: "DRB_data/uncal_sntemp_input_output_subset"
catchment_attr: "DRB_data/seg_attr_drb.feather"
dist_matrix: "DRB_data/distance_matrix_subset.npz"

out_dir: "DRB_output_subset_test"
code_dir: "river_dl"

x_vars: ["seg_rain", "seg_tave_air", "seginc_swrad", "seg_length", "seginc_potet", "seg_slope", "seg_humid", "seg_elev"]
gw_vars: ['Ar_obs','delPhi_obs','air_phi','air_amp','sin_wt','cos_wt']
primary_variable: "temp"
lamb: 0.5
#lamb2 and lamb3 are hyper params for weighting the rmses of Ar (amplitude ratio) and deltaPhi (phase difference)
lamb2: 2
lamb3: 0.1

#anything other than GW (case insensitive) will use the standard loss function (rmse of temp & rmse of flow)
loss_type: "GW"

pt_epochs: 200
ft_epochs: 100

train_start_date:
  - '1985-10-01'
train_end_date:
  - '2006-09-30'
val_start_date: '2006-10-01'
val_end_date: '2016-09-30'
test_start_date:
  - '1980-10-01'
test_end_date:
  - '1985-09-30'

hidden_size: 20
