# Input file
obs_file: "data_DRB/Obs_temp_flow_drb_full_no3558"
sntemp_file: "data_DRB/sntemp_inputs_outputs_drb_full_no3558"
dist_matrix_file: "data_DRB/distance_matrix_drb_full_no3558.npz"
reach_attr_file: "data_DRB/reach_attributes_drb.csv"

out_dir: "output_DRB_gw_type_test_linalg"

code_dir: "river_dl"

#x_vars: ["seg_rain", "seg_tave_air", "seginc_swrad", "seg_length", "seginc_potet", "seg_slope", "seg_humid", "seg_elev"]
x_vars: ['seg_ccov', 'seg_elev', 'seg_length', 'seg_rain', 'seg_slope', 'seg_tave_air', 'seg_tave_gw', 'seg_tave_ss', 'seg_tave_upstream', 'seg_upstream_inflow', 'seg_width', 'seginc_gwflow', 'seginc_potet', 'seginc_sroff', 'seginc_ssflow', 'seginc_swrad']

y_vars_pretrain: ['seg_tave_water']
y_vars_finetune: ['temp_c']
#y_vars_pretrain: ['seg_tave_water', 'seg_outflow']^M
##y_vars_finetune: ['temp_c', 'discharge_cms']^M


lambdas: [1]
#lambdas: [1,0]

#lambdas_gw are hyper params for weighting the rmses of Ar (amplitude ratio) and deltaPhi (phase difference)
lambdas_gw: [0, 0]

#gw loss calculation method, either 'fft' (fourier fast transform) or 'linalg' (linear algebra)
gw_loss_type: 'linalg'

trn_offset: 1.0
tst_val_offset: 1.0

train_start_date:
  - '1984-10-01'
  - '2015-10-01'
train_end_date:
  - '2010-09-30'
  - '2020-09-30'
val_start_date:
  - '1979-10-01'
  - '2010-10-01'
  - '2020-10-01'
val_end_date:
  - '1984-09-30'
  - '2015-09-30'
  - '2021-09-30'
test_start_date:
  - '1980-10-01'
  - '2020-10-01'
test_end_date:
  - '1985-09-30'
  - '2021-09-30'

pt_epochs: 200 
ft_epochs: 100

hidden_size: 20
