# Input files
obs_flow: "DRB_data/obs_flow_subset"
obs_temp: "DRB_data/obs_temp_subset"
sntemp_file: "DRB_data/uncal_sntemp_input_output_subset"
catchment_attr: "DRB_data/seg_attr_drb.feather"
dist_matrix: "DRB_data/distance_matrix_subset.npz"

out_dir: "DRB_outputs"
code_dir: "river_dl"

x_vars: ["seg_rain", "seg_tave_air", "seginc_swrad", "seg_length", "seginc_potet", "seg_slope", "seg_humid", "seg_elev"]
primary_variable: "temp"
lamb: 0
test_start_date: '2010-09-30'
n_test_yr: 6
pt_epochs: 200
ft_epochs: 100
hidden_size: 20
half_test: True
