# Input files^M
obs_file: "data_DRB/Obs_temp_flow_drb_full_no3558"^M
sntemp_file: "data_DRB/sntemp_inputs_outputs_drb_full_no3558"^M
dist_matrix: "data_DRB/distance_matrix_drb_full_no3558.npz"^M
reach_attr_file: "data_DRB/reach_attributes_drb.csv"^M

#x_vars: ["seg_rain", "seg_tave_air", "seginc_swrad", "seg_length", "seginc_potet", "seg_slope", "seg_humid", "seg_elev"]^M
x_vars: ['seg_ccov', 'seg_elev', 'seg_length', 'seg_rain', 'seg_slope', 'seg_tave_air', 'seg_tave_gw', 'seg_tave_ss', 'seg_tave_upstream', 'seg_upstream_inflow', 'seg_width', 'seginc_gwflow', 'seginc_potet', 'seginc_sroff', 'seginc_ssflow', 'seginc_swrad']^M

out_dir: "output_DRB_offsetTest"

code_dir: "river_dl"


y_vars_pretrain: ['seg_tave_water']
y_vars_finetune: ['temp_c']
#y_vars_pretrain: ['seg_tave_water', 'seg_outflow']
#y_vars_finetune: ['temp_c', 'discharge_cms']

lambdas: [1]
#lambdas: [1,0]

trn_offset: 1.0
tst_val_offset: 1.0

train_start_date:^M
  - '1984-10-01'^M
  - '2015-10-01'^M
train_end_date:^M
  - '2010-09-30'^M
  - '2020-09-30'^M
val_start_date:^M
  - '1979-10-01'^M
  - '2010-10-01'^M
  - '2020-10-01'^M
val_end_date:^M
  - '1984-09-30'^M
  - '2015-09-30'^M
  - '2021-09-30'^M
test_start_date:^M
  - '1980-10-01'^M
  - '2020-10-01'^M
test_end_date:^M
  - '1985-09-30'^M
  - '2021-09-30'^M


pt_epochs: 200
ft_epochs: 100
hidden_size: 20
