# Input files
obs_flow: "/home/jsadler/drb_data/obs_flow_full"
obs_temp: "/home/jsadler/drb_data/obs_temp_full"
sntemp_file: "/home/jsadler/drb_data/uncal_sntemp_input_output"
catchment_attr: "/home/jsadler/drb_data/seg_attr_drb.feather"
dist_matrix: "/home/jsadler/drb_data/distance_matrix.npz"

out_dir: "/caldera/projects/usgs/water/iidd/datasci/drb_ml_model/test_run2"
code_dir: "/home/jsadler/river-dl/river_dl"

x_vars: ["seg_rain", "seg_tave_air", "seginc_swrad", "seg_length", "seginc_potet", "seg_slope", "seg_humid", "seg_elev"]
primary_variable: "flow"
lamb: 1
test_start_date: '2010-09-30'
n_test_yr: 6
pt_epochs: 1
ft_epochs: 1
hidden_size: 20
half_test: True
