name: rgcn
channels:
    - conda-forge
    - defaults
    - bioconda
dependencies:
    - dask
    - ipython
    - matplotlib
    - pandas
    - pyarrow
    - scikit-learn
    - snakemake
    - tensorflow >= 2.0
    - tensorflow-gpu >= 2.0
    - xarray
    - zarr
